### PR TITLE
Added SplashScreen

### PR DESCRIPTION
**Pull request by aastikn**
Added an adaptive icon , icon as well as splash screen to the app in the assets folder.

### CODE REVIEW

**Comment by anandrajaram21** [comment]
Can you show a screenshot of the splash screen as well

**Comment by aastikn** [comment]
A preview of the App Icon and Splash screen

**Comment by aastikn** [comment]
Preview of how the app icon and the splash screens will look like:

App Icon   Splash

**Review by anandrajaram21 — COMMENTED** [review]
From the screenshot, the black splash screen looks quite jarring. Can you change the icon to have some contrast with the black background icon

**Comment by aastikn** [comment]
The black splash screen won't be displayed  cause I have set the background color white in the app.json

**Comment by aastikn** [comment]
Resolved #20 : SplashScreen

**Pull request closed without merging**
